# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-127400832-1'

menu:
- {name: 'Posts', path: 'menu', url: 'writing.html'}
- {name: 'Categories', path: 'menu', url: 'categories.html'}
- {name: 'About Me', path: 'menu', url: 'about.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {name: 'github', icon: 'github', link: 'https://github.com/shusunny/sunnyblog'}
- {name: 'facebook', icon: 'facebook-square', link: 'https://www.facebook.com/zhen.sun.589'}
- {name: 'instagram', icon: 'instagram', link: 'https://www.instagram.com/sunnnnnnyz/'}
- {name: 'weibo', icon: 'weibo', link: 'https://www.weibo.com/u/2670299603'}
- {name: 'linkedin', icon: 'linkedin', link: 'https://www.linkedin.com/in/shusunny/'}
- {name: 'flickr', icon: 'flickr', link: 'https://www.flickr.com/photos/144754548@N07/'}
- {name: 'email', icon: 'envelope', link: 'mailto:sunzhen1135@gmail.com'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
