# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: ''

menu:
- {name: 'Posts', path: 'menu', url: 'writing.html'}
- {name: 'Categories', path: 'menu', url: 'categories.html'}
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/shusunny'}
- {icon: 'twitter', link: 'https://twitter.com/sunzhen35'}
- {icon: 'weibo', link: 'https://www.weibo.com/u/2670299603'}
- {icon: 'instagram', link: 'https://www.instagram.com/sunnnnnnyz/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:sunzhen1135@gmail.com'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
